[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[program:app]
command=node /app/server.js
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=NODE_ENV="production",PORT="5000"

[program:cron]
command=node /app/cron/generate-blogs.js
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=NODE_ENV="production",PORT="5000"